import type { ProcessingRow } from "./processing-model";
import type { QaItem } from "./qa-model";

export const PREVIEW_PROCESSING_ROWS: ProcessingRow[] = [
  {
    id: "run-1",
    projectId: "harbor",
    projectName: "Harbor Street",
    source: "Room 4",
    kind: "gaussian_splat",
    stage: "train",
    status: "processing",
    statusLabel: "Processing",
    occurredAt: "2026-09-22T18:00:00.000Z",
    error: null,
    progressPct: 40,
    output: null,
  },
  {
    id: "fail-1",
    projectId: "annex",
    projectName: "Annex",
    source: "Sheet A2",
    kind: "Plans",
    stage: "rasterizing",
    status: "failed",
    statusLabel: "Failed",
    occurredAt: "2026-09-22T16:00:00.000Z",
    error: "The sheet could not be rasterized.",
    progressPct: null,
    output: null,
  },
  {
    id: "done-1",
    projectId: "harbor",
    projectName: "Harbor Street",
    source: "Room 2",
    kind: "gaussian_splat",
    stage: "export",
    status: "completed",
    statusLabel: "Completed",
    occurredAt: "2026-09-21T12:00:00.000Z",
    error: null,
    progressPct: null,
    output: "model-b",
  },
];

export const PREVIEW_QA_ITEMS: QaItem[] = [
  {
    projectId: "harbor",
    projectName: "Harbor Street",
    representation: "reality",
    sourceId: "model-b",
    title: "Room 4",
    version: "Sep 22, 2026",
    occurredAt: "2026-09-22T12:00:00.000Z",
    bucket: "needs_review",
    note: null,
    needsRecapture: false,
  },
  {
    projectId: "harbor",
    projectName: "Harbor Street",
    representation: "geometry",
    sourceId: "mesh-a",
    title: "Mesh",
    version: "Sep 20, 2026",
    occurredAt: "2026-09-20T12:00:00.000Z",
    bucket: "ready_to_publish",
    note: null,
    needsRecapture: false,
  },
  {
    projectId: "library",
    projectName: "Library",
    representation: "pano360",
    sourceId: "pano-1",
    title: "East stair",
    version: "Sep 14, 2026",
    occurredAt: "2026-09-14T12:00:00.000Z",
    bucket: "needs_review",
    note: null,
    needsRecapture: false,
  },
  {
    projectId: "drawings",
    projectName: "Drawings",
    representation: "plans",
    sourceId: "sheet-1",
    title: "A1.0",
    version: "Sep 1, 2026",
    occurredAt: "2026-09-01T12:00:00.000Z",
    bucket: "needs_review",
    note: null,
    needsRecapture: false,
  },
  {
    projectId: "harbor",
    projectName: "Harbor Street",
    representation: "reality",
    sourceId: "model-a",
    title: "Published model",
    version: "Aug 1, 2026",
    occurredAt: "2026-08-01T12:00:00.000Z",
    bucket: "published",
    note: null,
    needsRecapture: false,
  },
  {
    projectId: "annex",
    projectName: "Annex",
    representation: "reality",
    sourceId: "model-c",
    title: "Blurred",
    version: "Sep 18, 2026",
    occurredAt: "2026-09-18T12:00:00.000Z",
    bucket: "rejected",
    note: "West wall is too blurred.",
    needsRecapture: true,
  },
];
