/**
 * Real-capture YAML. Do not inherit configs/rgb/rgb_render_ex_r1.yml
 * (that file assumes synthetic GT poses).
 */

export function buildRealCaptureYaml({
  datasetPath,
  saveDir,
  width,
  height,
  odgsDir = "/opt/odgs-slam",
  downsampleAlreadyApplied = true,
} = {}) {
  const w = Number(width);
  const h = Number(height);
  const cx = w / 2;
  const cy = h / 2;
  const fx = w / 4;
  const fy = w / 4;
  const imageDownsample = downsampleAlreadyApplied ? 1 : 8;

  return `# Generated by Slate360 Research Processor V0.1
# CONFIRMED: no --eval, use_wandb false, use_gui false, no GT poses.
# EXPERIMENTAL: fx/fy/cx/cy are dummy pinhole fields required by the Camera class.
inherit_from: ${odgsDir}/configs/base_config.yml
Dataset:
  type: panorama
  sensor_type: monocular
  dataset_path: ${datasetPath}
  image_downsample: ${imageDownsample}
  Calibration:
    width: ${w}
    height: ${h}
    fx: ${fx}
    fy: ${fy}
    cx: ${cx}
    cy: ${cy}
    k1: 0.0
    k2: 0.0
    k3: 0.0
    p1: 0.0
    p2: 0.0
    depth_scale: 1.0
    distorted: false
Results:
  use_gui: false
  use_wandb: false
  eval_rendering: false
  save_results: true
  save_dir: ${saveDir}
  color_refine: false
Training:
  single_thread: true
`;
}
