#!/usr/bin/env bash
# WSL side of the GGPS research drop app. Wrap GGPS — do not vendor it.
# Usage: run_pipeline.sh --scene <wsl-scene-dir> --ggps <wsl-ggps-root> [--train] [--large-outdoor]
set -euo pipefail

SCENE=""
GGPS=""
DO_TRAIN=0
LARGE=0
SKIP_DAP=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --scene) SCENE="$2"; shift 2 ;;
    --ggps) GGPS="$2"; shift 2 ;;
    --train) DO_TRAIN=1; shift ;;
    --large-outdoor) LARGE=1; shift ;;
    --skip-dap) SKIP_DAP=1; shift ;;
    *) echo "unknown arg: $1"; exit 2 ;;
  esac
done

if [[ -z "$SCENE" || -z "$GGPS" ]]; then
  echo "need --scene and --ggps"
  exit 2
fi

echo "============================================================"
echo "Research — not for customer jobs"
echo "scene=$SCENE"
echo "ggps=$GGPS"
echo "============================================================"

IMAGES="$SCENE/images"
if [[ ! -d "$IMAGES" ]]; then
  echo "missing $IMAGES"
  exit 1
fi

OPENMVG_BIN="$(command -v openMVG_main_SfM || true)"
OPENSFM_PY="${OPENSFM_PY:-/home/rian_/slate360-engines/opensfm/.venv/bin/python}"
OPENSFM_SRC="${OPENSFM_SRC:-/home/rian_/slate360-engines/opensfm/source}"
EXPORT_PY="$(cd "$(dirname "$0")" && pwd)/export_opensfm_to_ggps.py"

sfm_ok=0

if [[ -n "$OPENMVG_BIN" ]]; then
  echo "[SfM] OpenMVG found at $OPENMVG_BIN"
  echo "[SfM] OpenMVG full CLI pipeline is not wired in v1 — use OpenSfM spherical instead, or drop a reconstruction/ from openMVG."
fi

if [[ -d "$SCENE/reconstruction" ]] && [[ -f "$SCENE/reconstruction/sfm_data_full.json" || -f "$SCENE/reconstruction/sfm_data.bin" ]]; then
  echo "[SfM] existing reconstruction/ found — skipping SfM"
  sfm_ok=1
  if [[ -f "$GGPS/scripts_new/prepare_pano_scene.sh" ]]; then
    echo "[prep] calling GGPS prepare_pano_scene.sh --skip-dap"
    bash "$GGPS/scripts_new/prepare_pano_scene.sh" --scene "$SCENE" --skip-dap || true
  fi
fi

if [[ "$sfm_ok" -eq 0 ]]; then
  if [[ ! -x "$OPENSFM_PY" ]]; then
    echo "[SfM] FAIL: OpenMVG not on PATH and OpenSfM python missing ($OPENSFM_PY)."
    echo "Install OpenMVG, or keep OpenSfM at ~/slate360-engines/opensfm."
    echo "Will NOT fall back to vanilla pinhole COLMAP on cube faces."
    exit 3
  fi
  echo "[SfM] OpenSfM spherical (not pinhole COLMAP)"
  SFM_DS="$SCENE/opensfm"
  mkdir -p "$SFM_DS/images"
  # OpenSfM wants images inside its dataset
  shopt -s nullglob
  for f in "$IMAGES"/*.{jpg,jpeg,png,JPG,JPEG,PNG}; do
    ln -sfn "$f" "$SFM_DS/images/$(basename "$f")"
  done
  shopt -u nullglob
  SFM_DS="$SFM_DS" python3 - <<'PY'
import json, os, struct
from pathlib import Path
root = Path(os.environ["SFM_DS"])
imgs = sorted(p for p in (root / "images").iterdir() if p.suffix.lower() in {".jpg", ".jpeg", ".png"})
if not imgs:
    raise SystemExit("no images for OpenSfM")
p = imgs[0]
data = p.read_bytes()
w = h = 0
if data[:2] == b"\xff\xd8":
    i = 2
    while i + 9 < len(data):
        if data[i] != 0xFF:
            i += 1
            continue
        marker = data[i + 1]
        if marker in (0xC0, 0xC1, 0xC2):
            h, w = struct.unpack(">HH", data[i + 5 : i + 9])
            break
        seglen = struct.unpack(">H", data[i + 2 : i + 4])[0]
        i += 2 + seglen
elif data[:8] == b"\x89PNG\r\n\x1a\n":
    w, h = struct.unpack(">II", data[16:24])
if w < 2 or h < 1:
    raise SystemExit("could not read image size")
print("ERP size %dx%d ratio=%.3f" % (w, h, w / float(h)))
(root / "config.yaml").write_text(
    "use_exif_size: no\nfeature_process_size: 2048\n"
    "matching_gps_distance: 0\nmatching_gps_neighbors: 0\n"
    "matching_order_neighbors: 12\nprocesses: 8\n"
    "align_method: naive\ndepthmap_num_neighbors: 0\n"
)
(root / "camera_models_overrides.json").write_text(
    json.dumps({"all": {"projection_type": "spherical", "width": w, "height": h}})
)
PY
  export PYTHONPATH="$OPENSFM_SRC:${PYTHONPATH:-}"
  MAIN="$OPENSFM_SRC/bin/opensfm_main.py"
  echo "[SfM] extract_metadata / detect_features / match_features / create_tracks / reconstruct"
  "$OPENSFM_PY" "$MAIN" extract_metadata "$SFM_DS"
  "$OPENSFM_PY" "$MAIN" detect_features "$SFM_DS"
  "$OPENSFM_PY" "$MAIN" match_features "$SFM_DS"
  "$OPENSFM_PY" "$MAIN" create_tracks "$SFM_DS"
  "$OPENSFM_PY" "$MAIN" reconstruct "$SFM_DS"
  if [[ ! -f "$SFM_DS/reconstruction.json" ]]; then
    echo "[SfM] FAIL: no reconstruction.json"
    exit 3
  fi
  python3 "$EXPORT_PY" "$SFM_DS" "$SCENE"
  sfm_ok=1
fi

if [[ ! -f "$SCENE/sparse/0/images.txt" ]]; then
  echo "[SfM] FAIL: sparse/0/images.txt missing"
  exit 3
fi

# yaml for coarse train — lives in the job, not inside GGPS git
SCENE_NAME="$(basename "$SCENE")"
YAML="$SCENE/${SCENE_NAME}.yaml"
cat > "$YAML" <<EOF
# Research — not for customer jobs. Generated by ggps-drop-app.
model_params: {
    model_config: {
        name: "GaussianModel",
        kwargs: {}
    },
    sh_degree: 3,
    source_path: "$SCENE",
    model_path: "$SCENE/output/${SCENE_NAME}_coarse",
    images: "imgs",
    alpha_masks: "",
    use_alpha_masks: False,
    use_sky_masks: False,
    use_depth: False,
    resolution: 1,
    white_background: False,
    data_device: "cpu",
    eval: True,
    skybox_num: 0,
    skybox_locked: True,
    default_camera_type: 3,
}
pipeline_params: {
    convert_SHs_python: False,
    compute_cov3D_python: False,
    debug: False
}
optim_params: {
    iterations: 30_000,
    position_lr_init: 0.00016,
    position_lr_final: 0.0000016,
    position_lr_delay_mult: 0.01,
    position_lr_max_steps: 30_000,
    feature_lr: 0.0025,
    opacity_lr: 0.025,
    scaling_lr: 0.005,
    rotation_lr: 0.001,
    percent_dense: 0.01,
    lambda_dssim: 0.2,
    densification_interval: 100,
    opacity_reset_interval: 3000,
    densify_from_iter: 500,
    densify_until_iter: 15_000,
    densify_grad_threshold: 0.0002,
    densify_grad_abs_threshold: 0.0004,
    prune_by_extent: false,
    depth_l1_weight_init: 0,
    depth_l1_weight_final: 0,
    max_cache_num: 512,
}
EOF
echo "[yaml] $YAML (default_camera_type: 3, use_depth: False)"

# imgs alias
if [[ ! -e "$SCENE/imgs" ]]; then
  ln -sfn images "$SCENE/imgs" || true
fi

if [[ "$DO_TRAIN" -ne 1 ]]; then
  echo "[train] skipped (SfM only). Output layout ready under $SCENE"
  exit 0
fi

PANO_PY=""
for c in \
  "$HOME/miniconda3/envs/PanoLOG/bin/python" \
  "$HOME/mambaforge/envs/PanoLOG/bin/python" \
  "$HOME/anaconda3/envs/PanoLOG/bin/python"
do
  if [[ -x "$c" ]]; then PANO_PY="$c"; break; fi
done
if [[ -z "$PANO_PY" ]] && command -v conda >/dev/null 2>&1; then
  PANO_PY="$(conda run -n PanoLOG which python 2>/dev/null || true)"
fi
if [[ -z "$PANO_PY" ]]; then
  echo "[train] PanoLOG python not found. One-time (WSL, sm_86 / RTX 3090):"
  echo "  conda create -yn PanoLOG python=3.9 pip && conda activate PanoLOG"
  echo "  pip install torch torchvision --index-url https://download.pytorch.org/whl/cu126"
  echo "  pip install -r $GGPS/requirements.txt"
  echo "  export TORCH_CUDA_ARCH_LIST=8.6 CUDA_HOME=/usr/local/cuda-12.6"
  echo "  pip install --no-build-isolation $GGPS/submodules/diff-gaussian-rasterization"
  echo "  pip install --no-build-isolation $GGPS/submodules/simple-knn"
  echo "SfM finished. Train after that env exists."
  exit 42
fi

export PYTHONPATH="$GGPS:${PYTHONPATH:-}"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
echo "[train] coarse train_large.py (Research — not for customer jobs)"
"$PANO_PY" "$GGPS/train_large.py" --config "$YAML"
PLY="$SCENE/output/${SCENE_NAME}_coarse/point_cloud/iteration_30000/point_cloud.ply"
if [[ -f "$PLY" ]]; then
  echo "[train] PLY $PLY"
else
  echo "[train] looking for any point_cloud.ply"
  find "$SCENE/output" -name 'point_cloud.ply' 2>/dev/null | head
fi

if [[ "$LARGE" -eq 1 ]]; then
  echo "[train] large outdoor: data_partition + per-block not auto-wired for indoor v1"
  echo "Copy config_360 templates *_c4.yaml and run data_partition.py by hand if you need campus-scale."
fi

echo "done. Research — not for customer jobs."
