import { EMAIL_COLORS as C } from "./email-theme";
/**
 * lib/email-site-walk.ts
 * Site Walk–specific email helpers. Extends the core email module.
 */
import { sendEmail, brandedHtml, ctaButton } from "@/lib/email";

/* ── Email: Deliverable Shared (Site Walk) ── */
export async function sendDeliverableShareEmail({
  to,
  senderName,
  deliverableTitle,
  deliverableType,
  shareUrl,
  expiresAt,
  message,
}: {
  to: string;
  senderName: string;
  deliverableTitle: string;
  deliverableType: string;
  shareUrl: string;
  expiresAt?: string;
  message?: string;
}) {
  const body = `
    <h2 style="margin:0 0 8px;color:${C.primary};font-size:24px;font-weight:800;">${senderName} shared a ${deliverableType} with you</h2>
    <p style="margin:0 0 18px;color:${C.textMuted};font-size:15px;line-height:1.7;">
      You've been sent <strong>"${deliverableTitle}"</strong> via Slate360 Site Walk.
    </p>
    ${
      message
        ? `<div style="margin:0 0 24px;padding:16px;background:${C.quoteBg};border-left:4px solid ${C.primary};border-radius:4px;color:${C.textBody};font-size:14px;font-style:italic;">"${message}"</div>`
        : ""
    }
    ${ctaButton("View Deliverable", shareUrl)}
    ${
      expiresAt
        ? `<p style="margin:20px 0 0;font-size:12px;color:${C.warning};font-weight:600;">
            ⚠️ This link expires on ${new Date(expiresAt).toLocaleDateString()}.
           </p>`
        : ""
    }
    <p style="margin:14px 0 0;font-size:12px;color:${C.textMuted};">
      No Slate360 account is required to view this deliverable.
    </p>`;

  return sendEmail({
    to,
    subject: `${senderName} shared "${deliverableTitle}" with you`,
    html: brandedHtml("Deliverable Shared", body),
  });
}

/* ── Email: Inline-image deliverable (photos render in the email body) ── */

export interface InlineImageItem {
  title: string;
  imageUrl: string;
  notes?: string;
}

export async function sendDeliverableInlineImageEmail({
  to,
  senderName,
  deliverableTitle,
  shareUrl,
  message,
  items,
}: {
  to: string;
  senderName: string;
  deliverableTitle: string;
  shareUrl: string;
  message?: string;
  items: InlineImageItem[];
}) {
  const photoBlocks = items
    .slice(0, 12)
    .map(
      (it) => `
        <div style="margin:0 0 24px;">
          <img src="${it.imageUrl}" alt="${escapeHtml(it.title)}" style="display:block;width:100%;max-width:520px;border-radius:8px;border:1px solid ${C.cardBorder};" />
          <div style="margin:8px 0 0;font-size:14px;font-weight:600;color:${C.textPrimary};">${escapeHtml(it.title)}</div>
          ${it.notes ? `<div style="margin:4px 0 0;font-size:13px;color:${C.textBody};line-height:1.5;">${escapeHtml(it.notes)}</div>` : ""}
        </div>`,
    )
    .join("");

  const overflow = items.length > 12
    ? `<p style="margin:0 0 16px;font-size:13px;color:${C.textMuted};">+ ${items.length - 12} more item${items.length - 12 === 1 ? "" : "s"} on the full page.</p>`
    : "";

  const body = `
    <h2 style="margin:0 0 8px;color:${C.primary};font-size:22px;font-weight:800;">${escapeHtml(senderName)} sent you "${escapeHtml(deliverableTitle)}"</h2>
    ${message ? `<div style="margin:0 0 20px;padding:14px;background:${C.quoteBg};border-left:4px solid ${C.primary};border-radius:4px;color:${C.textBody};font-size:14px;font-style:italic;">"${escapeHtml(message)}"</div>` : ""}
    ${photoBlocks}
    ${overflow}
    ${ctaButton("Open the full report", shareUrl)}
    <p style="margin:14px 0 0;font-size:12px;color:${C.textMuted};">No Slate360 account required.</p>`;

  return sendEmail({
    to,
    subject: `${senderName} sent you "${deliverableTitle}"`,
    html: brandedHtml(deliverableTitle, body),
  });
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/* ── Email: PDF Attachment deliverable ── */

export async function sendDeliverableAsPdfEmail({
  to,
  senderName,
  deliverableTitle,
  message,
  pdfBuffer,
  filename,
}: {
  to: string;
  senderName: string;
  deliverableTitle: string;
  message?: string;
  pdfBuffer: Buffer;
  filename: string;
}) {
  const body = `
    <h2 style="margin:0 0 8px;color:${C.primary};font-size:22px;font-weight:800;">${escapeHtml(senderName)} sent you a report</h2>
    <p style="margin:0 0 18px;color:${C.textMuted};font-size:15px;line-height:1.7;">
      Please find the PDF report attached for <strong>"${escapeHtml(deliverableTitle)}"</strong>.
    </p>
    ${message ? `<div style="margin:0 0 20px;padding:14px;background:${C.quoteBg};border-left:4px solid ${C.primary};border-radius:4px;color:${C.textBody};font-size:14px;font-style:italic;">"${escapeHtml(message)}"</div>` : ""}
    <p style="margin:14px 0 0;font-size:12px;color:${C.textMuted};">Generated by Slate360.</p>`;

  return sendEmail({
    to,
    subject: `${senderName} sent you a PDF report: "${deliverableTitle}"`,
    html: brandedHtml(deliverableTitle, body),
    attachments: [{ filename, content: pdfBuffer }],
  });
}
