"""Room 213 source-formation / detail-loss forensic audit (read-only, no training).

Traces ~30 frozen ROIs across: 1280 GT crop -> 640 downsample (steps 3000-5999 training
res) -> 320 downsample (steps 0-2999 training res) -> trained render (H5, where a
GT-vs-render panel exists for the ROI's station/view). Does NOT touch the original
Insta360 stitched ERP panorama or raw .insv (neither is available on this host -- see
the doc's "raw source" section for the designed-but-not-run comparison).

Inputs (all pre-existing, nothing generated by training):
  - GT crops:  <MIRROR>/views/images/<station>_v<vv>.jpg  (1280x1280, from the frozen
               `cecc2763` job's local scratch mirror -- same source as the camera-ray
               audit used)
  - Panels:    qa/exp3-run/exp5-pull/panels/panels/{best_000264,median_000173,worst_000325}.png
               (GT | render-H5 | render-G5 | diff, each ~1280 wide, v00 only)

Metrics per ROI per stage:
  - lapvar          variance of Laplacian (grayscale) -- overall HF/edge energy
  - hf_ratio         FFT energy fraction above 1/4 Nyquist
  - local_contrast   std of grayscale intensity within the ROI
  - michelson        (max-min)/(max+min) over the 1st/99th percentile band
  - esf_width_px     10-90% edge-spread width (px) at the strongest edge in the ROI
  - blockiness       mean |gradient| at 8x8 JPEG block boundaries / mean |gradient| elsewhere
                      (>1 indicates visible block-edge compression artifacts)
  - angular_px_per_deg  local angular sampling density at the ROI center, from the
                      pinhole model fl=640, density = fl / cos(theta)^2 per radian,
                      theta = atan(r/fl), r = distance from crop center (px)
"""
from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np
from PIL import Image

MIRROR = Path(r"C:\Users\bcvol\AppData\Local\Temp\claude\C--s360\dcf5d615-7c96-46b7-a919-75b63ec7cf34\scratchpad\room213\views\images")
PANELS = Path(r"C:\s360-recon-exp\qa\exp3-run\exp5-pull\panels\panels")
OUT = Path(r"C:\s360-recon-exp\docs\ops\room213-source-detail-audit")

FL = 640.0  # crop focal length in px (1280px crop, 90 deg HFOV) -- exact by construction


def lapvar(a: np.ndarray) -> float:
    a = a.astype(np.float32)
    L = (-4 * a + np.roll(a, 1, 0) + np.roll(a, -1, 0) + np.roll(a, 1, 1) + np.roll(a, -1, 1))[2:-2, 2:-2]
    return float(L.var())


def hf_ratio(a: np.ndarray) -> float:
    f = np.abs(np.fft.fftshift(np.fft.fft2(a.astype(np.float32) - a.mean())))
    h, w = f.shape
    yy, xx = np.mgrid[:h, :w]
    r = np.hypot(yy - h / 2, xx - w / 2) / (min(h, w) / 2)
    tot = f.sum()
    return float(f[r > 0.25].sum() / tot) if tot > 0 else 0.0


def local_contrast(a: np.ndarray) -> float:
    return float(a.astype(np.float32).std())


def michelson(a: np.ndarray) -> float:
    lo, hi = np.percentile(a, [1, 99])
    return float((hi - lo) / (hi + lo)) if (hi + lo) > 0 else 0.0


def esf_width_px(a: np.ndarray) -> float | None:
    """10-90% edge-spread width at the strongest edge in the ROI. Finds the pixel with
    max horizontal gradient magnitude, then measures the transition width along that row."""
    a = a.astype(np.float32)
    if a.shape[0] < 8 or a.shape[1] < 16:
        return None
    gx = np.abs(np.diff(a, axis=1))
    gx[:, :3] = 0
    gx[:, -3:] = 0
    idx = np.unravel_index(np.argmax(gx), gx.shape)
    row, col = idx
    lo = max(0, col - 15)
    hi = min(a.shape[1], col + 16)
    profile = a[row, lo:hi]
    if profile.max() == profile.min():
        return None
    norm = (profile - profile.min()) / (profile.max() - profile.min())
    rising = norm[-1] > norm[0]
    if not rising:
        norm = norm[::-1]
    below = np.where(norm < 0.1)[0]
    above = np.where(norm > 0.9)[0]
    if len(below) == 0 or len(above) == 0:
        return None
    i0 = below[-1] if below[-1] < (above[0] if len(above) else len(norm)) else below.max()
    candidates_below = below[below < above.max()] if len(above) else below
    if len(candidates_below) == 0:
        return None
    i0 = candidates_below.max()
    i1 = above[above > i0]
    if len(i1) == 0:
        return None
    return float(i1.min() - i0)


def blockiness(a: np.ndarray) -> float:
    a = a.astype(np.float32)
    h, w = a.shape
    gx = np.abs(np.diff(a, axis=1))
    cols = np.arange(gx.shape[1])
    on_block = (cols % 8) == 7
    if on_block.sum() == 0 or (~on_block).sum() == 0:
        return float("nan")
    return float(gx[:, on_block].mean() / (gx[:, ~on_block].mean() + 1e-6))


def box_downsample(a: np.ndarray, d: int) -> np.ndarray:
    """Exact equivalent of nerfstudio splatfacto's own resize_image() (splatfacto.py:110-121,
    "Downscale images using the same 'area' method in opencv": a dxd uniform-weight conv2d
    with stride=d) -- this is the LIVE per-step downscale splatfacto's _downscale_if_required()
    actually applies during the progressive-resolution training window, confirmed by reading
    the installed nerfstudio 1.1.5 source directly (not the unrelated PIL-BILINEAR resize in
    base_dataset.py's InputDataset.get_numpy_image, which is a different, unused code path
    here since camera_res_scale_factor=1.0 in every arm of this pipeline)."""
    h, w = a.shape
    h2, w2 = h // d, w // d
    return a[: h2 * d, : w2 * d].reshape(h2, d, w2, d).mean(axis=(1, 3))


def angular_density(cx_roi: float, cy_roi: float) -> float:
    r = math.hypot(cx_roi - 640, cy_roi - 640)
    theta = math.atan(r / FL)
    px_per_rad = FL / (math.cos(theta) ** 2)
    return px_per_rad * math.pi / 180.0


def stage_metrics(gray: np.ndarray, cx: float, cy: float) -> dict:
    return {
        "dims_px": list(gray.shape[::-1]),
        "lapvar": round(lapvar(gray), 2),
        "hf_ratio": round(hf_ratio(gray), 4),
        "local_contrast": round(local_contrast(gray), 2),
        "michelson": round(michelson(gray), 4),
        "esf_width_px": (round(w, 2) if (w := esf_width_px(gray)) is not None else None),
        "blockiness": round(blockiness(gray), 4),
    }


ROIS = [
    # station 000173 (median panel), v00 -- lens-center horizon, PANEL AVAILABLE
    dict(id="R01", station="000173", v="v00", cls="lens-center", category="ceiling-grid", bbox=(600, 80, 900, 320), note="main grid crossing, upper-center"),
    dict(id="R02", station="000173", v="v00", cls="lens-center", category="whiteboard", bbox=(740, 600, 1000, 780), note="whiteboard + flag area"),
    dict(id="R03", station="000173", v="v00", cls="lens-center", category="tabletop-object", bbox=(800, 850, 1050, 1180), note="red ladder rungs, fine repeating structure"),
    dict(id="R04", station="000173", v="v00", cls="lens-center", category="window-frame", bbox=(0, 480, 220, 900), note="left window + tree, frame/mullions"),
    dict(id="R05", station="000173", v="v00", cls="lens-center", category="carpet", bbox=(900, 1000, 1280, 1280), note="bottom-right carpet, yellow marks"),
    dict(id="R06", station="000173", v="v00", cls="lens-center", category="furniture-edge", bbox=(550, 900, 850, 1100), note="brown desk + metal slat hardware"),
    # station 000173, v02 -- yaw90 seam direction, NO panel
    dict(id="R07", station="000173", v="v02", cls="seam-yaw90", category="ceiling-grid", bbox=(600, 150, 950, 420), note="grid crossing"),
    dict(id="R08", station="000173", v="v02", cls="seam-yaw90", category="door-hardware", bbox=(30, 600, 180, 780), note="left wooden door, hinge/hardware"),
    dict(id="R09", station="000173", v="v02", cls="seam-yaw90", category="door-hardware", bbox=(300, 600, 420, 780), note="second door"),
    dict(id="R10", station="000173", v="v02", cls="seam-yaw90", category="chair-mesh", bbox=(990, 780, 1280, 980), note="mesh office chairs"),
    dict(id="R11", station="000173", v="v02", cls="seam-yaw90", category="whiteboard", bbox=(950, 600, 1150, 750), note="whiteboard, faint mark"),
    dict(id="R12", station="000173", v="v02", cls="seam-yaw90", category="carpet", bbox=(650, 850, 1000, 1100), note="yellow paint marks"),
    # station 000173, v06 -- yaw270 seam direction, NO panel
    dict(id="R13", station="000173", v="v06", cls="seam-yaw270", category="ceiling-grid", bbox=(550, 60, 900, 320), note="grid crossing"),
    dict(id="R14", station="000173", v="v06", cls="seam-yaw270", category="window-frame", bbox=(650, 500, 1280, 950), note="2 windows, tree/car through glass"),
    dict(id="R15", station="000173", v="v06", cls="seam-yaw270", category="chair-mesh", bbox=(370, 900, 620, 1150), note="front chair mesh, close/sharp"),
    dict(id="R16", station="000173", v="v06", cls="seam-yaw270", category="carpet", bbox=(0, 950, 300, 1200), note="shadow area"),
    # station 000173, v14 -- down-tilt / operator hemisphere, NO panel
    dict(id="R17", station="000173", v="v14", cls="down-operator", category="chair-mesh", bbox=(0, 250, 550, 700), note="stacked chairs, upper-left"),
    dict(id="R18", station="000173", v="v14", cls="down-operator", category="carpet", bbox=(700, 600, 1100, 900), note="yellow marks, down-tilt"),
    # station 000264 (best panel), v00 -- lens-center, PANEL AVAILABLE
    dict(id="R19", station="000264", v="v00", cls="lens-center", category="door-hardware", bbox=(130, 570, 290, 660), note="door closer bar"),
    dict(id="R20", station="000264", v="v00", cls="lens-center", category="door-hardware", bbox=(350, 800, 440, 920), note="door lever/deadbolt"),
    dict(id="R21", station="000264", v="v00", cls="lens-center", category="wall-sign-text", bbox=(455, 585, 540, 650), note="small room-number wall sign"),
    dict(id="R22", station="000264", v="v00", cls="lens-center", category="chair-mesh", bbox=(575, 845, 745, 1030), note="chair back"),
    dict(id="R23", station="000264", v="v00", cls="lens-center", category="carpet", bbox=(900, 950, 1280, 1200), note="yellow marks"),
    dict(id="R24", station="000264", v="v00", cls="lens-center", category="whiteboard", bbox=(870, 700, 1280, 760), note="pen tray + reflections"),
    # station 000325 (worst panel), v00 -- lens-center, PANEL AVAILABLE
    dict(id="R25", station="000325", v="v00", cls="lens-center", category="ceiling-grid", bbox=(550, 20, 900, 250), note="grid crossing"),
    dict(id="R26", station="000325", v="v00", cls="lens-center", category="window-frame", bbox=(0, 540, 650, 950), note="window bank"),
    dict(id="R27", station="000325", v="v00", cls="lens-center", category="whiteboard", bbox=(860, 510, 1210, 930), note="blank whiteboard, edge/frame"),
    dict(id="R28", station="000325", v="v00", cls="lens-center", category="tabletop-object", bbox=(390, 760, 530, 880), note="blue crate"),
    dict(id="R29", station="000325", v="v00", cls="lens-center", category="tabletop-object", bbox=(850, 760, 1150, 980), note="yellow straps on rolled material"),
    dict(id="R30", station="000325", v="v00", cls="lens-center", category="carpet", bbox=(0, 1050, 300, 1280), note="foreground"),
]

PANEL_FOR_STATION = {"000173": "median_000173", "000264": "best_000264", "000325": "worst_000325"}


def load_gray(path: Path) -> np.ndarray:
    return np.asarray(Image.open(path).convert("L"))


def crop_box(a: np.ndarray, bbox: tuple[int, int, int, int]) -> np.ndarray:
    x0, y0, x1, y1 = bbox
    return a[y0:y1, x0:x1]


def main() -> None:
    results = []
    panel_cache: dict[str, np.ndarray] = {}

    for roi in ROIS:
        gt_path = MIRROR / f"{roi['station']}_v{roi['v'][1:]}.jpg"
        gt_full = load_gray(gt_path)
        bbox = roi["bbox"]
        cx = (bbox[0] + bbox[2]) / 2
        cy = (bbox[1] + bbox[3]) / 2

        gt_roi = crop_box(gt_full, bbox)
        w, h = bbox[2] - bbox[0], bbox[3] - bbox[1]

        gt640 = box_downsample(gt_full, 2)
        gt320 = box_downsample(gt_full, 4)
        bbox640 = tuple(int(v / 2) for v in bbox)
        bbox320 = tuple(int(v / 4) for v in bbox)
        gt_roi_640 = crop_box(gt640, bbox640)
        gt_roi_320 = crop_box(gt320, bbox320)

        stages = {
            "1280_crop": stage_metrics(gt_roi, cx, cy),
            "640_downsample": stage_metrics(gt_roi_640, cx / 2, cy / 2) if gt_roi_640.size else None,
            "320_downsample": stage_metrics(gt_roi_320, cx / 4, cy / 4) if gt_roi_320.size else None,
        }

        render_stage = None
        if roi["v"] == "v00" and roi["station"] in PANEL_FOR_STATION:
            pname = PANEL_FOR_STATION[roi["station"]]
            if pname not in panel_cache:
                panel_cache[pname] = load_gray(PANELS / f"{pname}.png")
            panel = panel_cache[pname]
            seg_w = panel.shape[1] // 4
            gt_seg = panel[:, :seg_w]
            render_seg = panel[:, seg_w:2 * seg_w]
            # panel segments are ~1280-wide GT-aligned crops; bbox applies directly
            # (clip in case the segment is a few px narrower than 1280)
            bx = (min(bbox[0], seg_w - 1), bbox[1], min(bbox[2], seg_w), bbox[3])
            render_roi = crop_box(render_seg, bx)
            gt_seg_roi = crop_box(gt_seg, bx)
            if render_roi.size and gt_seg_roi.size:
                render_stage = stage_metrics(render_roi, cx, cy)
                render_stage["gt_cross_check_lapvar"] = round(lapvar(gt_seg_roi), 2)
                render_stage["gt_cross_check_matches_mirror"] = abs(
                    lapvar(gt_seg_roi) - stages["1280_crop"]["lapvar"]
                ) < 0.15 * max(1.0, stages["1280_crop"]["lapvar"])

        stages["trained_render_h5"] = render_stage

        results.append({
            "id": roi["id"], "station": roi["station"], "view": roi["v"],
            "direction_class": roi["cls"], "category": roi["category"], "note": roi["note"],
            "bbox_1280": list(bbox), "roi_dims_px": [w, h],
            "angular_px_per_deg_at_center": round(angular_density(cx, cy), 2),
            "stages": stages,
        })

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "roi_results.json").write_text(json.dumps(results, indent=2), encoding="utf-8")

    # console summary
    for r in results:
        s = r["stages"]
        render = s["trained_render_h5"]
        print(
            f"{r['id']} {r['category']:16s} {r['direction_class']:14s} "
            f"1280 lv={s['1280_crop']['lapvar']:8.1f} esf={s['1280_crop']['esf_width_px']} "
            f"640 lv={s['640_downsample']['lapvar']:8.1f} "
            f"320 lv={s['320_downsample']['lapvar']:8.1f} "
            + (f"render lv={render['lapvar']:8.1f} ratio={render['lapvar']/max(1,s['1280_crop']['lapvar']):.2f}" if render else "render n/a")
        )


if __name__ == "__main__":
    main()
